version: 0.1
phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install -U pytest
      - sls plugin install -n serverless-python-requirements
  pre_build:
    commands:
      - python -m pytest
  build:
    commands:
      - sls deploy --stage $STAGE